// admin/lib/styles.ts
// The style object S — migrated from App.jsx inline styles

export const S = {
  loginWrap: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "#F7F2EA",
    fontFamily: "var(--admin-sans)",
  } as React.CSSProperties,
  loginCard: {
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.25)",
    borderRadius: 24,
    padding: 40,
    width: 380,
    boxShadow: "0 20px 50px rgba(153, 134, 117, 0.15)",
    position: "relative",
    overflow: "hidden",
  } as React.CSSProperties,
  loginLogo: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 8,
  } as React.CSSProperties,
  logoIcon: { color: "#C8A96B", display: "flex" } as React.CSSProperties,
  logoText: {
    fontFamily: "var(--admin-heading)",
    fontSize: 24,
    fontWeight: 700,
    letterSpacing: 4,
    color: "#1F3D5A",
  } as React.CSSProperties,
  loginSub: {
    color: "#64748b",
    fontSize: 13,
    marginBottom: 28,
    marginTop: 0,
  } as React.CSSProperties,

  sidebar: {
    width: 250,
    flexShrink: 0,
    background: "#1F3D5A",
    borderRight: "1px solid rgba(200, 169, 107, 0.15)",
    display: "flex",
    flexDirection: "column",
    height: "100vh",
    position: "sticky",
    top: 0,
    overflowY: "auto",
  } as React.CSSProperties,
  sidebarHeader: {
    padding: "22px 20px 18px",
    display: "flex",
    alignItems: "center",
    gap: 10,
    borderBottom: "1px solid rgba(200, 169, 107, 0.15)",
  } as React.CSSProperties,
  sidebarLogoText: {
    fontFamily: "var(--admin-heading)",
    fontSize: 18,
    fontWeight: 700,
    letterSpacing: 3,
    color: "#FFFFFF",
  } as React.CSSProperties,
  sidebarSection: { padding: "18px 12px 8px" } as React.CSSProperties,
  sidebarSectionLabel: {
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: 2,
    color: "#a2b4c7",
    textTransform: "uppercase",
    paddingLeft: 8,
    marginBottom: 6,
  } as React.CSSProperties,
  navItem: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    width: "100%",
    padding: "10px 12px",
    borderRadius: 12,
    borderTop: "none",
    borderRight: "none",
    borderBottom: "none",
    borderLeft: "3px solid transparent",
    background: "transparent",
    color: "#cbd5e1",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    textAlign: "left",
    transition: "all .15s",
  } as React.CSSProperties,
  navItemActive: {
    background: "rgba(200,169,107,.15)",
    color: "#C8A96B",
    borderLeft: "3px solid #C8A96B",
    borderRadius: "0 12px 12px 0",
  } as React.CSSProperties,
  navDot: {
    width: 5,
    height: 5,
    borderRadius: "50%",
    background: "currentColor",
    opacity: 0.4,
    flexShrink: 0,
  } as React.CSSProperties,
  sidebarFooter: {
    marginTop: "auto",
    padding: 14,
    borderTop: "1px solid rgba(200, 169, 107, 0.15)",
    display: "flex",
    alignItems: "center",
    gap: 10,
  } as React.CSSProperties,
  userBadge: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flex: 1,
    overflow: "hidden",
  } as React.CSSProperties,
  userAvatar: {
    width: 30,
    height: 30,
    borderRadius: 8,
    background: "linear-gradient(135deg,#1F3D5A,#C8A96B)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 700,
    fontSize: 13,
    color: "#fff",
    flexShrink: 0,
  } as React.CSSProperties,
  userName: {
    fontSize: 13,
    fontWeight: 600,
    color: "#FFFFFF",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  userRole: { fontSize: 11, color: "#a2b4c7" } as React.CSSProperties,
  logoutBtn: {
    background: "transparent",
    border: "none",
    color: "#a2b4c7",
    cursor: "pointer",
    padding: 6,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
  } as React.CSSProperties,

  shell: {
    display: "flex",
    minHeight: "100vh",
    background: "#FAF9F6",
    fontFamily: "var(--admin-sans)",
    color: "#1E293B",
  } as React.CSSProperties,
  mainContent: { flex: 1, overflow: "auto" } as React.CSSProperties,

  pageWrap: {
    padding: "28px 32px",
    maxWidth: 1200,
    position: "relative",
  } as React.CSSProperties,
  pageHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    marginBottom: 24,
    gap: 16,
  } as React.CSSProperties,
  breadcrumb: {
    fontSize: 12,
    color: "#64748b",
    marginBottom: 8,
    display: "flex",
    alignItems: "center",
  } as React.CSSProperties,
  pageTitle: {
    fontSize: 28,
    fontWeight: 500,
    fontFamily: "var(--admin-heading)",
    color: "#1F3D5A",
    margin: 0,
    letterSpacing: "-0.5px",
  } as React.CSSProperties,
  pageSubtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 4,
  } as React.CSSProperties,
  centerFlex: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "60vh",
    color: "#64748b",
  } as React.CSSProperties,

  dashGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(220px,1fr))",
    gap: 16,
    marginTop: 8,
  } as React.CSSProperties,
  dashCard: {
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.15)",
    borderRadius: 16,
    padding: "24px 20px",
    cursor: "pointer",
    textAlign: "left",
    transition: "all .2s",
    display: "flex",
    flexDirection: "column",
    gap: 6,
    position: "relative",
    overflow: "hidden",
    boxShadow: "0 4px 20px rgba(153,134,117,0.04)",
  } as React.CSSProperties,
  dashCardIcon: {
    color: "#C8A96B",
    opacity: 0.8,
    marginBottom: 4,
  } as React.CSSProperties,
  dashCardName: {
    fontWeight: 700,
    fontSize: 16,
    color: "#1F3D5A",
  } as React.CSSProperties,
  dashCardSub: { fontSize: 12, color: "#64748b" } as React.CSSProperties,
  dashCardArrow: {
    position: "absolute",
    top: 22,
    right: 18,
    color: "#C8A96B",
    opacity: 0.7,
  } as React.CSSProperties,

  toolbar: {
    display: "flex",
    gap: 10,
    marginBottom: 16,
    alignItems: "center",
  } as React.CSSProperties,
  searchWrap: {
    position: "relative",
    flex: 1,
    maxWidth: 360,
  } as React.CSSProperties,
  searchIcon: {
    position: "absolute",
    left: 12,
    top: "50%",
    transform: "translateY(-50%)",
    color: "#64748b",
    pointerEvents: "none",
  } as React.CSSProperties,
  searchInput: {
    width: "100%",
    padding: "10px 12px 10px 38px",
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.15)",
    borderRadius: 12,
    color: "#1E293B",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    boxShadow: "0 2px 10px rgba(0,0,0,0.02)",
  } as React.CSSProperties,

  tableWrap: {
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.2)",
    borderRadius: 18,
    overflowX: "auto",
    WebkitOverflowScrolling: "touch",
    boxShadow: "0 6px 24px rgba(153, 134, 117, 0.06)",
  } as React.CSSProperties,
  table: {
    width: "100%",
    minWidth: 800,
    borderCollapse: "collapse",
    fontSize: 13,
  } as React.CSSProperties,
  th: {
    padding: "16px 20px",
    textAlign: "left",
    color: "#5A4E3E",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    borderBottom: "1px solid rgba(200, 169, 107, 0.18)",
    background: "#F7F2EA",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  tr: { transition: "background .15s ease" } as React.CSSProperties,
  td: {
    padding: "16px 20px",
    borderBottom: "1px solid rgba(200, 169, 107, 0.08)",
    color: "#1E293B",
    verticalAlign: "middle",
    whiteSpace: "nowrap",
  } as React.CSSProperties,
  emptyCell: {
    padding: 48,
    textAlign: "center",
    color: "#64748b",
    fontSize: 14,
  } as React.CSSProperties,
  tableLoadingWrap: {
    padding: 48,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#64748b",
  } as React.CSSProperties,

  badge: {
    green: {
      background: "rgba(34,197,94,.12)",
      color: "#15803D",
      padding: "3px 10px",
      borderRadius: 9999,
      fontSize: 11,
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      fontWeight: 700,
    } as React.CSSProperties,
    red: {
      background: "rgba(220,38,38,.12)",
      color: "#B91C1C",
      padding: "3px 10px",
      borderRadius: 9999,
      fontSize: 11,
      display: "inline-flex",
      alignItems: "center",
      gap: 5,
      fontWeight: 700,
    } as React.CSSProperties,
    gray: {
      background: "rgba(100,116,139,.12)",
      color: "#475569",
      padding: "3px 10px",
      borderRadius: 9999,
      fontSize: 11,
      fontWeight: 700,
    } as React.CSSProperties,
    gold: {
      background: "rgba(200,169,107,.14)",
      color: "#998675",
      padding: "3px 10px",
      borderRadius: 9999,
      fontSize: 11,
      fontWeight: 700,
    } as React.CSSProperties,
  },

  actionBtn: {
    background: "#FAF9F6",
    border: "1px solid rgba(200, 169, 107, 0.22)",
    borderRadius: 8,
    padding: "7px 11px",
    color: "#1F3D5A",
    cursor: "pointer",
    marginLeft: 6,
    display: "inline-flex",
    alignItems: "center",
    transition: "all .15s",
    boxShadow: "0 1px 3px rgba(0,0,0,0.02)",
  } as React.CSSProperties,
  actionBtnDanger: {
    color: "#dc2626",
    borderColor: "rgba(220,38,38,.2)",
    background: "rgba(220,38,38,.04)",
  } as React.CSSProperties,

  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 0",
    marginTop: 8,
  } as React.CSSProperties,
  paginationInfo: { fontSize: 13, color: "#64748b" } as React.CSSProperties,

  modalOverlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(31,61,90,.3)",
    backdropFilter: "blur(8px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
    padding: 20,
  } as React.CSSProperties,
  modalCard: {
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.2)",
    borderRadius: 24,
    width: "100%",
    maxWidth: 640,
    maxHeight: "90vh",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 30px 90px rgba(31,61,90,0.12)",
    overflow: "hidden",
  } as React.CSSProperties,
  modalHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "20px 24px",
    borderBottom: "1px solid rgba(200, 169, 107, 0.12)",
    background: "#FAF9F6",
  } as React.CSSProperties,
  modalTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 700,
    fontFamily: "var(--admin-heading)",
    color: "#1F3D5A",
  } as React.CSSProperties,
  modalClose: {
    background: "transparent",
    border: "none",
    color: "#64748b",
    cursor: "pointer",
    padding: 6,
    borderRadius: 6,
    display: "flex",
    alignItems: "center",
  } as React.CSSProperties,
  modalBody: { padding: "24px", overflow: "auto" } as React.CSSProperties,

  formGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill,minmax(260px,1fr))",
    gap: 20,
  } as React.CSSProperties,
  formField: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } as React.CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "#475569",
    letterSpacing: 0.5,
  } as React.CSSProperties,
  input: {
    padding: "10px 12px",
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.18)",
    borderRadius: 10,
    color: "#1E293B",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
    width: "100%",
    fontFamily: "inherit",
  } as React.CSSProperties,
  inputError: { borderColor: "#dc2626" } as React.CSSProperties,
  fieldError: { fontSize: 12, color: "#dc2626" } as React.CSSProperties,
  helpText: { fontSize: 11, color: "#64748b" } as React.CSSProperties,
  errorBanner: {
    background: "rgba(220,38,38,.1)",
    border: "1px solid rgba(220,38,38,.2)",
    borderRadius: 8,
    padding: "10px 12px",
    color: "#dc2626",
    fontSize: 13,
  } as React.CSSProperties,

  btn: {
    display: "inline-flex",
    alignItems: "center",
    gap: 7,
    padding: "10px 20px",
    borderRadius: 10,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    border: "1px solid transparent",
    transition: "all .15s",
    fontFamily: "inherit",
  } as React.CSSProperties,
  btnPrimary: {
    background: "linear-gradient(135deg, #1F3D5A 0%, #152a3f 100%)",
    color: "#FFFFFF",
    border: "none",
    boxShadow: "0 4px 12px rgba(31,61,90,0.15)",
  } as React.CSSProperties,
  btnGhost: {
    background: "transparent",
    border: "1px solid rgba(200, 169, 107, 0.2)",
    color: "#1F3D5A",
  } as React.CSSProperties,

  toast: {
    position: "fixed",
    bottom: 24,
    right: 24,
    background: "#FFFFFF",
    border: "1px solid rgba(200, 169, 107, 0.2)",
    borderLeft: "4px solid #C8A96B",
    borderRadius: 12,
    padding: "14px 20px",
    color: "#1E293B",
    fontSize: 14,
    zIndex: 2000,
    boxShadow: "0 8px 32px rgba(153,134,117,.15)",
    maxWidth: 340,
  } as React.CSSProperties,

  // Drop zone
  dropZone: {
    border: "2px dashed rgba(200, 169, 107, 0.25)",
    borderRadius: 16,
    padding: "32px 24px",
    textAlign: "center",
    cursor: "pointer",
    transition: "all .2s",
    background: "#FAF9F6",
    marginBottom: 4,
  } as React.CSSProperties,
  dropZoneActive: {
    borderColor: "#C8A96B",
    background: "rgba(200,169,107,.04)",
  } as React.CSSProperties,
  dropZoneIcon: {
    color: "#C8A96B",
    display: "flex",
    justifyContent: "center",
    marginBottom: 10,
    transform: "scale(1.3)",
  } as React.CSSProperties,
  dropZoneText: {
    color: "#64748b",
    fontSize: 14,
    fontWeight: 500,
    marginBottom: 4,
  } as React.CSSProperties,
  dropZoneSub: { color: "#64748b", fontSize: 12 } as React.CSSProperties,
} as const;

// Re-export React for the `as React.CSSProperties` casts
import React from "react";
